### ISSUE TITLE
Split add-on authors into a collection

### ISSUE THREAD

**Issue by DemianWright** [McTwist/Blockland-Repository#39]
Currently the add-on authors is just a string that can contain whatever. It needs to be split into a collection of strings, because that is what it is. This will make dealing with it easier in views for truncation and so on.

Eventually you should be able to select add-on authors from the list of Blockland Repository users and the author names should be links to their user pages (on the add-on page), but that is an issue for another day. This would be the first step in that direction.

**Comment by McTwist** [comment]
This would also make it easier search for authors. Moving them to an another table and have a pivot table to link them would be good enough. Sadly, I cannot link them with the current user table as that is a whole different story. I could, however, make an another pivot table to link the authors table together with the user table, but we'll see how I'll deal with that.

**Comment by McTwist** [comment]
547ab94516c12cc7d9bb494239b23112503aab1f solves this issue.
