### ISSUE TITLE
Fix category icon colors and bleed

### ISSUE THREAD

**Issue by DemianWright** [McTwist/Blockland-Repository#5]
All category icons have 1px of bleed at the bottom due to the drop shadow. Additionally the category icon gradients should be changed to use the defined color palette.

**Comment by McTwist** [comment]
~~SpeedKart are bleeding more than 1px.~~
Scratch that. 7fa03e05a929318b29e6deb407096a4ada96a224 fixed it.

**Comment by DemianWright** [comment]
Nope. I have only fixed 2 icons so far, 30 to go.
