### ISSUE TITLE
Fix add-on upload button not working as intended

### ISSUE THREAD

**Issue by DemianWright** [McTwist/Blockland-Repository#6]
Commit 9c817b5dfc9f5983d4830f68e0cc7f8f2ac63bec broke the JavaScript on the browse file button in the add-on upload view. The functionality works but you must press the button twice and you get an error in the browser console because of it.

I believe the issue is simply that you need to initialize Dropzone after the upload div has loaded but I couldn't get it working.

**Comment by DemianWright** [comment]
Additionally it would be nice if you were unable to press the button while the file is uploading.

**Comment by McTwist** [comment]
Init should not happen when you click on the button. I'll try to find a way to init it properly and apply the changes to the button.

**Comment by McTwist** [comment]
Fixed it and added more candy around it.

**Comment by DemianWright** [comment]
Reopening because you can still press the button while the file is uploading. While this doesn't cause any real issues, it is not user friendly.

**Comment by McTwist** [comment]
Fixed the issue on 3102b7c0ee3d58f50fa7b5b5be0b9b38b284eb7d.
